[package]


version = "0.0.1"

# Description
category = "isaaclab"
readme  = "README.md"

title = "RL Extension Library for Robots, Based on IsaacLab."
author = "Zhi Liu"
description="Isaac Lab Extension for Legged Robot Locomotion"
keywords = ["extension", "isaaclab"]

[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.core" = {}
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}

# Main python module this extension provides.
[[python.module]]
name = "eilab_tasks"
