[package]
version = "0.0.1"
title = "Legged Robot extension"
description="Isaac Lab Extension for Legged Robot Locomotion"
category = "robotics"
keywords = ["kit", "robotics"]
readme  = "docs/README.md"

[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.core" = {}
"saaclab" = {}

# Main python module this extension provides.
[[python.module]]
name = "leggedloco_tasks"
